<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Работа с шаблонами</title>
</head>
<body>
    <h1>Привет, мир!</h1>
    <!-- <input type = "text" name = "email" placeholder= "Введите email">
    <input type = "text" name = "email" placeholder= "Введите email">
    <button type = "submit">Отправить<button> -->
</body>
</html>